App_Accounts/urls.py
from django.urls import path 
from App_Accounts import views 

app_name = "App_Accounts" 

urlpatterns = [
    path('signup/', views.sign_up, name='sign_up'), 
    path('login/', views.log_in, name='log_in'),
    # path('edit/', views.edit_profile, name='edit_profile'), 
    path('logout/', views.logout_user, name='logout'), 
    # path('profile/', views.profile, name='profile'),
    # path('user/<username>/', views.user, name='user'),
    # path('follow/<username>', views.follow, name='follow'),
    # path('unfollow/<username>', views.unfollow, name='unfollow'),
]

App_Posts/urls.py
from django.urls import path
from App_Posts import views 

app_name = 'App_Posts'

urlpatterns = [
    path("", views.home, name='home'),
    path('post/<int:post_id>/', views.post_view, name='post_view')
]

Dj_Video_Streaming/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from App_Posts import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Accounts.urls')),
    path('posts/', include('App_Posts.urls')),
    path('', views.home, name='home')
]

# urlpatterns += staticfiles_urlpatterns()    # may be used for STATIC files only. we're not using any static file so far
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Accounts/models.py
from django.db import models
from django.contrib.auth.models import User 

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    full_name = models.CharField(max_length=264, blank=True)

    def __str__(self):
        return f"{self.user}" 

App_Posts/models.py
from django.db import models
from django.contrib.auth.models import User 


class Post(models.Model):
    CATEGORY_CHOICES = [
        ('javascript', 'JavaScript'),
        ('python', 'Python'),
        ('php', 'PHP'),
    ]
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    title = models.CharField(max_length=264, blank=True) 
    category = models.CharField(max_length=40, choices=CATEGORY_CHOICES, default=None)
    description = models.TextField(blank=True)
    video_link = models.URLField(blank=True) 
    upload_date = models.DateField(auto_now_add=True)

    class Meta: 
        ordering = ['-upload_date',]  # try using the string '?' for random ordering
    
    def __str__(self):
        return f"{self.title} ({self.category})"



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='commented_post')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='commenter')
    comment = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True) 

    def __str__(self):
        return f"{self.user}, {self.post}" 

App_Accounts/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.models import User 


class CreateNewUser(UserCreationForm):
    email = forms.EmailField(required=True, label="", widget=forms.TextInput(attrs={'placeholder':'Email'}))
    username = forms.CharField(required=True, label="", widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password1 = forms.CharField(
        required = True, 
        label = "",
        widget = forms.PasswordInput(attrs={'placeholder':'Password'})
    )
    password2 = forms.CharField(
        required = True, 
        label = "",
        widget = forms.PasswordInput(attrs={'placeholder':'Confirm password'})
    )

    class Meta:
        model = User 
        fields = ('email', 'username', 'password1', 'password2')

App_Posts/forms.py
from django import forms 
from App_Posts.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta: 
        model = Post 
        fields = ['title', 'description', 'video_link']



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']
        widgets = {
            'comment': forms.Textarea(attrs={'rows': 2, 'cols': 30}),  
        }

App_Accounts/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from App_Accounts.forms import CreateNewUser
from App_Accounts.models import UserProfile
from django.contrib.auth.forms import AuthenticationForm  # to authenticate the user's credential 
from django.contrib.auth import authenticate, login, logout 
from django.contrib.auth.decorators import login_required

def sign_up(request):
    form = CreateNewUser()
    if request.method == 'POST':
        form = CreateNewUser(data=request.POST)
        if form.is_valid():
            user = form.save()
            user_profile = UserProfile(user=user)
            user_profile.save() 
            return HttpResponseRedirect(reverse('App_Accounts:log_in'))  # change it to 'App_Post:home', also pass user info when logged in 
    
    context={ 'title':'Sign up . V-Stream', 'form' : form }

    return render(request, 'App_Accounts/signup.html', context)


def log_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None: 
                login(request, user)
                return HttpResponseRedirect(reverse('App_Posts:home')) 
    
    context={'title':'Login . V-Stream', 'form':form}

    return render(request, 'App_Accounts/login.html', context)

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Accounts:log_in'))

App_Posts/views.py
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from App_Posts.models import Post, Comment
from App_Posts.forms import CommentForm
from django.contrib.auth.models import User 
from django.db.models import Q  # used for complex queries


def home(request):
    posts = Post.objects.all()

    if request.method == 'GET':
        search = request.GET.get('search', '')
        result = Post.objects.filter(Q(title__icontains=search) | Q(category__icontains=search))   # Q is used for complex queries 
        context={
            'title':'Home . V-Streaming', 
            'search':search, 
            'result':result, 
            'posts':posts, 
        }
    return render(request, 'App_Posts/home.html', context)



# ***********WE'RE WORKING HERE***********

def post_view(request, post_id):
    post = Post.objects.get(id=post_id)
    form = CommentForm()

    comments = Comment.objects.filter(post=post)
    print(comments)

    if request.method == 'POST':
        form = CommentForm(data=request.POST)
        if form.is_valid():
            text = form.cleaned_data.get('comment')
            comment = Comment(post=post, user=request.user, comment=text)
            comment.save()
            return HttpResponseRedirect(reverse('App_Posts:post_view', args=[post_id]))
            
    context = {
        'title' : 'post_view . v-stream', 
        'post' : post, 
        'form' : form,
        'comments' : comments
    }

    return render(request, 'App_Posts/post_view.html', context)

templates/App_Accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% block title_block %} {{title}} {% endblock %}

{% block css_block %} 
<style>
    .container
    {
        height: 800px;
    }
    .log_in
    {
        width: 450px;
        border: 1px solid #ccc;
        border-radius: 2.5%;
        box-shadow: 5px 5px 10px #888888;
        padding: 30px;
        margin: 20px;
    }
</style>
{% endblock %}

{% block body_block %}
<section class="container d-flex justify-content-center align-items-center">
    <div class="log_in">
        <form method="POST">
            {{form|crispy}}
            {% csrf_token %}
            <button type="submit" style="width:100%" class="btn btn-primary"> Log in </button> 
        </form>
        <p class="text-center mt-2">Don't have any account? <a href="{% url 'App_Accounts:sign_up' %}">Sign up</a></p>
    </div>
</section>
{% endblock %}

templates/App_Accounts/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{title}} {% endblock %}

{% block css_block %} 
<style>
    .container
    {
        height: 800px;
    }
    .sign_up
    {
        width: 450px;
        border: 1px solid #ccc;
        border-radius: 2.5%;
        box-shadow: 5px 5px 10px #888888;
        padding: 30px;
        margin: 20px;
    }
</style>
{% endblock %}

{% block body_block %}
<section class="container d-flex justify-content-center align-items-center">
    <div class="sign_up">
        <h5 class="text-center mb-3">Sign up to see photos of your friends</h5>
        <form method="POST">
            {{ form|crispy }}
            {% csrf_token %}
            <button type="submit" style="width:100%" class="btn btn-primary"> Sign up </button> 
        </form>
        <p class="text-center mt-2">Have an account? <a href="{% url 'App_Accounts:log_in' %}">Log in</a></p>
    </div>
</section>
{% endblock %}

templates/App_Posts/home.html
{% extends 'navbar.html' %}
{% block title_block %} {{title}} {% endblock %}

{% block body_block%}

    {% if search %}
        <h3>Search matched {{result|length}} results</h3>
        <div class="row row-cols-2 row-cols-md-4">
            {% for video in result %}
                <div class="col my-2">
                    <div class="mx-1">
                        <iframe
                            class="card-img-top"
                            src="{{video.video_link}}"
                            frameborder="0"
                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                            allowfullscreen>
                        </iframe>
                        <div>
                            <div class="d-flex justify-content-between">
                                <small><h6 class="text-info">{{video.category|title}}</h6></small>  <!-- 'title' is used to capitalize the text (category name) -->
                                <a href="{% url 'App_Posts:post_view' post_id=video.id %}" class="btn btn-secondary">View</a>
                            </div>
                            <h6>{{video.title}}</h6>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>


        {% else %}
            <div class="row row-cols-2 row-cols-md-4">
                {% for video in posts %}
                    <div class="col my-2">
                        <div class="mx-1">
                            <iframe
                                class="card-img-top"
                                src="{{video.video_link}}"
                                frameborder="0"
                                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                allowfullscreen>
                            </iframe>
                            <div>
                                <div class="d-flex justify-content-between">
                                    <small><h6 class="text-info">{{video.category|title}}</h6></small>  <!-- 'title' is used to capitalize the text (category name) -->
                                    <a href="{% url 'App_Posts:post_view' post_id=video.id %}" class="btn btn-secondary">View</a>
                                </div>
                                <h6>{{video.title}}</h6>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
    {% endif %}

{% endblock %}

templates/App_Posts/post_view.html
{% extends 'navbar.html' %}
{% load crispy_forms_tags %} 
{% block title_block %} {{title}} {% endblock %}

{% block body_block%}

    <div class="m-2">
        <iframe
            width="1000px"
            height="500px"
            src="{{post.video_link}}"
            frameborder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowfullscreen>
        </iframe>
        <div>
            <small><h4 class="text-info">{{post.category|title}}</h4></small>  <!-- 'title' is used to capitalize the text (category name) -->
            <h3>{{post.title}}</h3>
        </div>
    </div>

    <div class="m-2">
        <form method="POST">
            {{form|crispy}}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary"> Send </button> 
        </form>
    </div> 

    <h4>Comments:</h4>
    {% if comments %}
        <div class="container p-3  bg-light border rounded">
            {% for comment in comments %}
                <div class="row px-3 my-2">
                    <div class="col-1">
                        <a class="nav-link" href="#"><img src="/media/profile_pic/default_user.png" height="40px" width="40px" class="rounded-circle"></a>
                    </div>
                    <div class="col-11">
                        <div class="row"><h6>{{comment.user}}</h6></div>
                        <div class="row"><p>{{comment.comment}}</p></div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title_block %}V-Stream{% endblock %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Popper.js (library to manage poppers) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js" integrity="sha512-2rNj2KJ+D8s1ceNasTIex6z4HWyOnEYLVC3FigGOmyQCZc2eBXKgOxQmo3oKLHyfcj53uz4QMsRCWNbLd32Q1g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script> 
    {% block css_block %} {% endblock %}
</head>
<body>
    <div class="container">
        {% block body_block %} {% endblock %}
    </div>
</body>
</html>

templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title_block %}Social{% endblock %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Popper.js (library to manage poppers) -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js" integrity="sha512-2rNj2KJ+D8s1ceNasTIex6z4HWyOnEYLVC3FigGOmyQCZc2eBXKgOxQmo3oKLHyfcj53uz4QMsRCWNbLd32Q1g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script> 

    <!-- Font awesome icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block css_block %} {% endblock %}
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'App_Posts:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            &nbsp; &nbsp; &nbsp; &nbsp;
            <!-- Search form -->
            <form class="form-inline" method="GET">
              <input class="form-control mr-sm-2" type="text" name="search" placeholder="Search">
              <button class="btn btn-success" type="submit">Search</button>
            </form>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'App_Accounts:logout' %}"><span class="text-danger">Log out</span> <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item row">
              <div class="col">
                <a class="nav-link" href="#"><img src="/media/profile_pic/default_user.png" height="40px" width="40px" class="rounded-circle"></a>
              </div>
              <div class="col">
                {{request.user}}
              </div>
            </li>
          </ul>
        </div>
      </nav>

    <div class="container p-3">
        {% block body_block %} {% endblock %}
    </div>
</body>
</html>